### ISSUE TITLE
JSON issue

### ISSUE THREAD

**Issue by codeschris** [aaanh/gpt-test-bench#1]
While running the Single-Turn prompt, it returns a prompt:

`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

What could be the issue?

**Comment by codeschris** [comment]
I used the demo version for the public

**Comment by aaanh** [comment]
This is due to OpenAI API slow response coupled with Vercel's highly restrictive edge function execution time. Since it's a publicly available demo, though the restrictions are inconvenient, they are somewhat intended.

Edit: I've now also deprecated the single-turn module in favor of the multi-turn, now renamed to 'chat', as it can achieve everything the single turn could and more.
